########################
# SLURM DOCKER CLUSTER #
########################

## VOLUMES
volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:

## SERVICES
services:

  # MariaDB
  mysql:
    image: mariadb:11
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  # SlurmDBd
  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG:-24.05.1}
    build:
      context: .
      args:
        SLURM_TAG: ${SLURM_TAG:-slurm-24-05-1-1}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    environment: 
      PUID: 990
      GUID: 990
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  # Slurmctld
  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG:-24.05.1}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    environment: 
      PUID: 990
      GUID: 990
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  # Compute node 1
  compute1:
    image: slurm-docker-cluster:${IMAGE_TAG:-24.05.1}
    command: ["slurmd"]
    hostname: compute1
    container_name: compute1
    environment: 
      PUID: 990
      GUID: 990
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  # Compute node 2
  compute2:
    image: slurm-docker-cluster:${IMAGE_TAG:-24.05.1}
    command: ["slurmd"]
    hostname: compute2
    container_name: compute2
    environment: 
      PUID: 990
      GUID: 990
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

